// src/lib/templates_mock_webpage/funky/Newsletter.svelte
<script lang="ts">
	import { Button } from '$lib/components/ui/button';
	import { Input } from '$lib/components/ui/input';
	import { Mail, Gift } from 'lucide-svelte';
	
	export let sectionTitle: string = 'Get 20% Off Your First Order! 🎉';
	export let sectionDescription: string = 'Join our funky fashion community and be the first to know about new collections, exclusive deals, and style tips. Plus, get an instant discount!';
	export let primaryColor: string = '#9333ea';
	export let secondaryColor: string = '#ec4899';
</script>

<section class="py-20 px-6 md:px-12">
	<div class="container mx-auto">
		<div class="relative overflow-hidden rounded-3xl p-12 md:p-16 text-white" style="background: linear-gradient(to bottom right, {primaryColor}, {secondaryColor}, #f97316);">
			<!-- Animated Background Shapes -->
			<div class="absolute top-0 right-0 w-64 h-64 bg-white/10 rounded-full blur-3xl" />
			<div class="absolute bottom-0 left-0 w-80 h-80 bg-white/10 rounded-full blur-3xl" />

			<div class="relative z-10 max-w-3xl mx-auto text-center">
				<div class="inline-block mb-6">
					<div class="w-20 h-20 bg-white/20 backdrop-blur-lg rounded-full flex items-center justify-center mx-auto">
						<Gift class="w-10 h-10" />
					</div>
				</div>

				<h2 class="text-4xl md:text-5xl mb-4">
					{sectionTitle}
				</h2>

				<p class="text-purple-100 mb-8 max-w-2xl mx-auto">
					{sectionDescription}
				</p>

				<div class="flex flex-col sm:flex-row gap-4 max-w-md mx-auto">
					<div class="flex-1 relative">
						<Mail class="absolute left-4 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
						<Input
							type="email"
							placeholder="Enter your email"
							class="pl-12 h-14 rounded-full bg-white text-gray-900 border-none"
						/>
					</div>
					<Button class="h-14 px-8 rounded-full bg-gray-900 hover:bg-gray-800 text-white">
						Subscribe Now
					</Button>
				</div>

				<div class="flex items-center justify-center gap-6 mt-8 text-sm text-purple-100">
					<div class="flex items-center gap-2">
						<div class="w-5 h-5 bg-white/20 rounded-full flex items-center justify-center">✓</div>
						No spam
					</div>
					<div class="flex items-center gap-2">
						<div class="w-5 h-5 bg-white/20 rounded-full flex items-center justify-center">✓</div>
						Unsubscribe anytime
					</div>
					<div class="flex items-center gap-2">
						<div class="w-5 h-5 bg-white/20 rounded-full flex items-center justify-center">✓</div>
						Exclusive deals
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

// Example-websites-UI/Funky/src/components/Newsletter.tsx
import { motion } from "motion/react";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Mail, Gift } from "lucide-react";

export function Newsletter() {
  return (
    <section className="py-20 px-6 md:px-12">
      <div className="container mx-auto">
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          whileInView={{ opacity: 1, scale: 1 }}
          viewport={{ once: true }}
          className="relative overflow-hidden bg-gradient-to-br from-purple-600 via-pink-600 to-orange-500 rounded-3xl p-12 md:p-16 text-white"
        >
          {/* Animated Background Shapes */}
          <motion.div
            animate={{ rotate: 360, scale: [1, 1.2, 1] }}
            transition={{ duration: 20, repeat: Infinity }}
            className="absolute top-0 right-0 w-64 h-64 bg-white/10 rounded-full blur-3xl"
          />
          <motion.div
            animate={{ rotate: -360, scale: [1, 1.3, 1] }}
            transition={{ duration: 25, repeat: Infinity }}
            className="absolute bottom-0 left-0 w-80 h-80 bg-white/10 rounded-full blur-3xl"
          />

          <div className="relative z-10 max-w-3xl mx-auto text-center">
            <motion.div
              initial={{ scale: 0 }}
              whileInView={{ scale: 1 }}
              viewport={{ once: true }}
              transition={{ type: "spring", stiffness: 200 }}
              className="inline-block mb-6"
            >
              <div className="w-20 h-20 bg-white/20 backdrop-blur-lg rounded-full flex items-center justify-center mx-auto">
                <Gift className="w-10 h-10" />
              </div>
            </motion.div>

            <motion.h2
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className="text-4xl md:text-5xl mb-4"
            >
              Get 20% Off Your First Order! 🎉
            </motion.h2>

            <motion.p
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.1 }}
              className="text-purple-100 mb-8 max-w-2xl mx-auto"
            >
              Join our funky fashion community and be the first to know about new collections,
              exclusive deals, and style tips. Plus, get an instant discount!
            </motion.p>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.2 }}
              className="flex flex-col sm:flex-row gap-4 max-w-md mx-auto"
            >
              <div className="flex-1 relative">
                <Mail className="absolute left-4 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
                <Input
                  type="email"
                  placeholder="Enter your email"
                  className="pl-12 h-14 rounded-full bg-white text-gray-900 border-none"
                />
              </div>
              <Button className="h-14 px-8 rounded-full bg-gray-900 hover:bg-gray-800 text-white">
                Subscribe Now
              </Button>
            </motion.div>

            <motion.div
              initial={{ opacity: 0 }}
              whileInView={{ opacity: 1 }}
              viewport={{ once: true }}
              transition={{ delay: 0.3 }}
              className="flex items-center justify-center gap-6 mt-8 text-sm text-purple-100"
            >
              <div className="flex items-center gap-2">
                <div className="w-5 h-5 bg-white/20 rounded-full flex items-center justify-center">
                  ✓
                </div>
                No spam
              </div>
              <div className="flex items-center gap-2">
                <div className="w-5 h-5 bg-white/20 rounded-full flex items-center justify-center">
                  ✓
                </div>
                Unsubscribe anytime
              </div>
              <div className="flex items-center gap-2">
                <div className="w-5 h-5 bg-white/20 rounded-full flex items-center justify-center">
                  ✓
                </div>
                Exclusive deals
              </div>
            </motion.div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
