// src/lib/templates_mock_webpage/funky/HeroSection.svelte
<script lang="ts">
	import { Button } from '$lib/components/ui/button';
	import { Sparkles, ArrowRight } from 'lucide-svelte';
	import ImageWithFallback from './ImageWithFallback.svelte';
	
	export let heroImage: string = '';
	export let heroTitle: string = 'BOLD. FUNKY. FEARLESS.';
	export let heroDescription: string = 'Express yourself with fashion that speaks your language. Bold designs, vibrant colors, and fearless style.';
	export let heroBadge: string = 'New Collection 2024';
	export let ctaPrimary: string = 'Shop Now';
	export let ctaSecondary: string = 'Explore';
	export let primaryColor: string = '#9333ea';
	export let secondaryColor: string = '#ec4899';
</script>

<section class="relative min-h-screen overflow-hidden bg-gradient-to-br from-purple-50 to-pink-50">
	<!-- Animated Background Elements -->
	<div class="absolute top-20 left-10 w-32 h-32 bg-gradient-to-br from-pink-400 to-purple-500 rounded-full blur-3xl opacity-60" />
	<div class="absolute bottom-20 right-10 w-40 h-40 bg-gradient-to-br from-yellow-400 to-orange-500 rounded-full blur-3xl opacity-60" />

	<!-- Navigation -->
	<nav class="relative z-20 flex items-center justify-between px-6 md:px-12 py-6">
		<div class="flex items-center gap-2">
			<Sparkles class="w-8 h-8" style="color: {primaryColor};" />
			<span class="tracking-wider font-bold" style="color: {primaryColor};">FUNKIFY</span>
		</div>
		<div class="hidden md:flex gap-8">
			<a href="#" class="text-gray-700 hover:opacity-70 transition-colors">Men</a>
			<a href="#" class="text-gray-700 hover:opacity-70 transition-colors">Women</a>
			<a href="#" class="text-gray-700 hover:opacity-70 transition-colors">Collections</a>
			<a href="#" class="text-gray-700 hover:opacity-70 transition-colors">About</a>
		</div>
		<Button variant="outline" style="border-color: {primaryColor}; color: {primaryColor};" class="hover:opacity-90">
			Shop Now
		</Button>
	</nav>

	<!-- Hero Content -->
	<div class="relative z-10 container mx-auto px-6 md:px-12 grid md:grid-cols-2 gap-12 items-center mt-12 md:mt-0">
		<div class="space-y-6">
			<div class="inline-block px-4 py-2 rounded-full" style="background: linear-gradient(to right, {primaryColor}, {secondaryColor}); color: white;">
				{heroBadge}
			</div>
			<h1 class="text-6xl md:text-8xl text-gray-900 leading-tight">
				<span class="bg-gradient-to-r from-purple-600 via-pink-600 to-orange-500 bg-clip-text text-transparent">
					{heroTitle.split('.')[0]}.
				</span>
				<br />
				<span class="text-gray-800">{heroTitle.split('.')[1]}.</span>
				<br />
				<span class="bg-gradient-to-r from-pink-600 to-orange-500 bg-clip-text text-transparent">
					{heroTitle.split('.')[2]}.
				</span>
			</h1>
			<p class="text-xl text-gray-600 max-w-lg">
				{heroDescription}
			</p>
			<div class="flex flex-wrap gap-4">
				<Button size="lg" style="background: linear-gradient(to right, {primaryColor}, {secondaryColor});" class="text-white hover:opacity-90">
					{ctaPrimary}
					<ArrowRight class="ml-2 h-4 w-4" />
				</Button>
				<Button size="lg" variant="outline" class="border-2 hover:bg-gray-100">
					{ctaSecondary}
				</Button>
			</div>
		</div>

		<div class="relative">
			<ImageWithFallback
				src={heroImage}
				alt="Hero image"
				className="rounded-3xl shadow-2xl"
			/>
		</div>
	</div>
</section>

// react-templates/Funky/src/components/HeroSection.tsx
import { motion } from "motion/react";
import { Button } from "./ui/button";
import { Sparkles, ArrowRight } from "lucide-react";
import { ImageWithFallback } from "./figma/ImageWithFallback";
import type { BrandConfig } from "../shared-brand-config";

interface HeroSectionProps {
  brandConfig: BrandConfig;
}

export function HeroSection({ brandConfig }: HeroSectionProps) {
  const { colorPalette, logoUrl, brandName, brandDescription, images, features } = brandConfig;
  
  // Create gradient strings from brand colors
  const gradient1 = `linear-gradient(to bottom right, ${colorPalette.secondary}, ${colorPalette.primary})`;
  const gradient2 = `linear-gradient(to bottom right, ${colorPalette.accent}, ${colorPalette.secondary})`;
  const heroGradient = `linear-gradient(to right, ${colorPalette.primary}, ${colorPalette.secondary})`;
  const textGradient1 = `linear-gradient(to right, ${colorPalette.primary}, ${colorPalette.secondary}, ${colorPalette.accent})`;
  const textGradient2 = `linear-gradient(to right, ${colorPalette.accent}, ${colorPalette.secondary}, ${colorPalette.primary})`;
  const imageGradient = `linear-gradient(to right, ${colorPalette.primary}, ${colorPalette.secondary}, ${colorPalette.accent})`;

  return (
    <section className="relative min-h-screen overflow-hidden">
      {/* Animated Background Elements */}
      <motion.div
        className="absolute top-20 left-10 w-32 h-32 rounded-full blur-3xl opacity-60"
        style={{ background: gradient1 }}
        animate={{
          scale: [1, 1.2, 1],
          x: [0, 30, 0],
          y: [0, -20, 0],
        }}
        transition={{ duration: 8, repeat: Infinity }}
      />
      <motion.div
        className="absolute bottom-20 right-10 w-40 h-40 rounded-full blur-3xl opacity-60"
        style={{ background: gradient2 }}
        animate={{
          scale: [1, 1.3, 1],
          x: [0, -40, 0],
          y: [0, 30, 0],
        }}
        transition={{ duration: 10, repeat: Infinity }}
      />

      {/* Navigation */}
      <motion.nav
        initial={{ y: -100 }}
        animate={{ y: 0 }}
        className="relative z-20 flex items-center justify-between px-6 md:px-12 py-6"
      >
        <div className="flex items-center gap-2">
          {logoUrl ? (
            <img src={logoUrl} alt={brandName} className="h-8 w-auto" />
          ) : (
            <Sparkles className="w-8 h-8" style={{ color: colorPalette.primary }} />
          )}
          <span className="tracking-wider font-bold" style={{ color: colorPalette.primary }}>
            {brandName}
          </span>
        </div>
        <div className="hidden md:flex gap-8">
          {features.slice(0, 4).map((feature, index) => (
            <a
              key={index}
              href="#"
              className="transition-colors"
              style={{ 
                color: colorPalette.text,
              }}
              onMouseEnter={(e) => e.currentTarget.style.color = colorPalette.primary}
              onMouseLeave={(e) => e.currentTarget.style.color = colorPalette.text}
            >
              {feature.title}
            </a>
          ))}
        </div>
        <Button
          variant="outline"
          style={{
            borderColor: colorPalette.primary,
            color: colorPalette.primary,
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.backgroundColor = colorPalette.primary;
            e.currentTarget.style.color = '#ffffff';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.backgroundColor = 'transparent';
            e.currentTarget.style.color = colorPalette.primary;
          }}
        >
          Shop Now
        </Button>
      </motion.nav>

      {/* Hero Content */}
      <div className="relative z-10 container mx-auto px-6 md:px-12 grid md:grid-cols-2 gap-12 items-center mt-12 md:mt-0">
        <motion.div
          initial={{ opacity: 0, x: -50 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.8 }}
          className="space-y-6"
        >
          <motion.div
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: 0.2 }}
            className="inline-block px-4 py-2 text-white rounded-full"
            style={{ background: heroGradient }}
          >
            {brandConfig.industry} Collection 2024
          </motion.div>
          <h1 className="text-6xl md:text-8xl leading-tight" style={{ color: colorPalette.text }}>
            <span
              className="bg-clip-text text-transparent"
              style={{
                backgroundImage: textGradient1,
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
              }}
            >
              {features[0]?.title || "BOLD."}
            </span>
            <br />
            <span style={{ color: colorPalette.text }}>{brandName}</span>
            <br />
            <span
              className="bg-clip-text text-transparent"
              style={{
                backgroundImage: textGradient2,
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
              }}
            >
              {features[1]?.title || "FEARLESS."}
            </span>
          </h1>
          <p className="max-w-md" style={{ color: colorPalette.text, opacity: 0.7 }}>
            {brandDescription}
          </p>
          <div className="flex gap-4">
            <Button
              style={{
                background: heroGradient,
                color: '#ffffff',
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.opacity = '0.9';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.opacity = '1';
              }}
            >
              Explore Collection <ArrowRight className="ml-2 w-4 h-4" />
            </Button>
            <Button variant="outline" style={{ borderColor: colorPalette.primary, color: colorPalette.primary }}>
              Watch Video
            </Button>
          </div>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, x: 50 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.8, delay: 0.2 }}
          className="relative"
        >
          <motion.div
            animate={{ rotate: [0, 5, 0, -5, 0] }}
            transition={{ duration: 6, repeat: Infinity }}
            className="relative z-10"
          >
            <div
              className="absolute -inset-4 rounded-3xl blur-2xl opacity-50"
              style={{ background: imageGradient }}
            />
            <ImageWithFallback
              src={images.hero || "https://images.unsplash.com/photo-1685432531593-1afc8a152e5f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYXNoaW9uJTIwbW9kZWwlMjBydW53YXl8ZW58MXx8fHwxNzYzNzEzNjM1fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral"}
              alt={brandName}
              className="relative rounded-3xl shadow-2xl w-full h-[600px] object-cover"
            />
          </motion.div>

          {/* Floating Tags */}
          {features.slice(0, 2).map((feature, index) => (
            <motion.div
              key={index}
              animate={{ y: [0, index === 0 ? -10 : 10, 0] }}
              transition={{ duration: 3 + index * 1, repeat: Infinity, delay: index * 0.5 }}
              className="absolute bg-white px-6 py-3 rounded-full shadow-xl"
              style={{
                top: index === 0 ? '2.5rem' : 'auto',
                bottom: index === 1 ? '5rem' : 'auto',
                left: index === 0 ? '-1.5rem' : 'auto',
                right: index === 1 ? '-1.5rem' : 'auto',
                borderWidth: '2px',
                borderColor: index === 0 ? colorPalette.primary + '40' : colorPalette.secondary + '40',
              }}
            >
              <span style={{ color: index === 0 ? colorPalette.primary : colorPalette.secondary }}>
                {index === 0 ? '✨ ' : '🔥 '}{feature.title}
              </span>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
}
