// react-templates/Minimalistic/src/components/Hero.tsx
import { ArrowRight } from "lucide-react";
import { Button } from "./ui/button";
import { ImageWithFallback } from "./figma/ImageWithFallback";
import { BrandConfig } from "../shared-brand-config";

interface HeroProps {
  brandConfig: BrandConfig;
}

export function Hero({ brandConfig }: HeroProps) {
  return (
    <section className="relative overflow-hidden px-6 py-12 md:py-16">
      <div className="mx-auto max-w-7xl">
        <div className="grid items-center gap-12 lg:grid-cols-2">
          <div>
            <div 
              className="mb-6 inline-block rounded-full border px-4 py-1.5"
              style={{ 
                borderColor: brandConfig.colorPalette.accent,
                color: brandConfig.colorPalette.text 
              }}
            >
              {brandConfig.industry} Excellence
            </div>
            
            <h1 
              className="mb-6 text-5xl md:text-6xl font-bold"
              style={{ 
                color: brandConfig.colorPalette.text,
                fontFamily: brandConfig.fonts.heading 
              }}
            >
              {brandConfig.brandName}
            </h1>
            
            <p 
              className="mb-8 max-w-xl text-lg"
              style={{ color: brandConfig.colorPalette.text, opacity: 0.8 }}
            >
              {brandConfig.brandDescription}
            </p>
            
            <div className="flex flex-wrap items-center gap-4">
              <Button 
                className="text-white"
                style={{ backgroundColor: brandConfig.colorPalette.primary }}
              >
                Explore Collection
                <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
              <Button 
                variant="outline" 
                style={{ 
                  borderColor: brandConfig.colorPalette.accent,
                  color: brandConfig.colorPalette.text 
                }}
              >
                Learn More
              </Button>
            </div>

            {/* Stats */}
            <div className="mt-12 grid grid-cols-3 gap-8 border-t pt-8" style={{ borderColor: brandConfig.colorPalette.accent }}>
              {brandConfig.stats.map((stat, idx) => (
                <div key={idx}>
                  <div 
                    className="mb-1 text-2xl font-bold"
                    style={{ color: brandConfig.colorPalette.text }}
                  >
                    {stat.value}
                  </div>
                  <div className="text-sm" style={{ color: brandConfig.colorPalette.text, opacity: 0.7 }}>
                    {stat.label}
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="relative">
            <ImageWithFallback
              src={brandConfig.images.hero || "https://images.unsplash.com/photo-1708758487256-8a3a73565dc2?w=1080"}
              alt={`${brandConfig.brandName} hero`}
              className="relative rounded-2xl shadow-xl"
            />
          </div>
        </div>
      </div>
    </section>
  );
}

// src/lib/templates_mock_webpage/minimalistic/Hero.svelte
<script lang="ts">
	import { ArrowRight } from 'lucide-svelte';
	import { Button } from '$lib/components/ui/button';
	import ImageWithFallback from './ImageWithFallback.svelte';
	
	export let heroImage: string = '';
	export let heroTitle: string = 'Pure Design, Timeless Comfort';
	export let heroDescription: string = 'Discover our curated collection of minimalist furniture. Each piece crafted in classic black and white to bring elegance and simplicity to your space.';
	export let heroBadge: string = 'Minimal Living Collection';
	export let ctaPrimary: string = 'Explore Collection';
	export let ctaSecondary: string = 'View Lookbook';
	export let primaryColor: string = '#030213';
	export let stats: Array<{ value: string; label: string }> = [
		{ value: '500+', label: 'Products' },
		{ value: '50k+', label: 'Happy Homes' },
		{ value: 'Free', label: 'Delivery' }
	];
</script>

<section class="relative overflow-hidden px-6 py-12 md:py-16">
	<div class="mx-auto max-w-7xl">
		<div class="grid items-center gap-12 lg:grid-cols-2">
			<div>
				<div class="mb-6 inline-block rounded-full border border-neutral-200 px-4 py-1.5 text-neutral-600">
					{heroBadge}
				</div>
				
				<h1 class="mb-6 text-neutral-900">
					{heroTitle}
				</h1>
				
				<p class="mb-8 max-w-xl text-neutral-600">
					{heroDescription}
				</p>
				
				<div class="flex flex-wrap items-center gap-4">
					<Button style="background-color: {primaryColor};" class="hover:opacity-90">
						{ctaPrimary}
						<ArrowRight class="ml-2 h-4 w-4" />
					</Button>
					<Button variant="outline" class="border-neutral-300 text-neutral-900 hover:bg-neutral-50">
						{ctaSecondary}
					</Button>
				</div>

				<!-- Stats -->
				<div class="mt-12 grid grid-cols-3 gap-8 border-t border-neutral-200 pt-8">
					{#each stats as stat}
						<div>
							<div class="mb-1 text-neutral-900">
								{stat.value}
							</div>
							<div class="text-neutral-600">{stat.label}</div>
						</div>
					{/each}
				</div>
			</div>

			<div class="relative">
				<ImageWithFallback
					src={heroImage}
					alt="Hero image"
					className="relative rounded-2xl shadow-xl"
				/>
			</div>
		</div>
	</div>
</section>
